llm_cfg_path: /home/ubuntu/co-training/models/llama2-7b/ 
llm_dtype_name: float16
llm_ckpt_path: /home/ubuntu/co-training/deepspeed-test/llama2-pipe/
llm_model_type: llama
llm_lora_rank: 1
llm_lora_alpha: 1
llm_lora_dropout: 0.1
llm_lora_ckpt_save_path: ckpts/demos/llama2-7b/
ds_config_path: configs/ds_cfg/ds_config_pp4.yml
gnn_loss_type: gcn
gnn_num_nodes: 169343
gnn_node_features: 1024
gnn_layers: 2
gnn_use_leading: false
gnn_leading_alpha: 0.1
gnn_dtype_name: float16
gnn_dropout: 0.1
gnn_neighbor_num: 10
gnn_ckpt_save_path: ckpts/demos/gnn/
dataset_name: ogbn-arxiv
dataset_path: /home/ubuntu/co-training/deepspeed-test/demos/dataset/
dataset_tokenized_ids_cache: cache/ogbn-arxiv/tokenized_ids_cache.pkl
dataset_padding_width: 512
dataloader_type: dgl
