resume: false
llm_cfg_path: /home/jupyter/models/opt-1.3b
llm_dtype_name: float16
llm_ckpt_path: opt-1.3b/
llm_model_type: opt
llm_lora_rank: 8
llm_lora_alpha: 32
llm_lora_dropout: 0.1
llm_lora_ckpt_save_path: ckpts/demos/opt-1.3b/
llm_use_checkpoint: false
ds_config_path: configs/ds_cfg/ds_pp4_16G_opt1.3b.yaml
gnn_loss_type: gcn
gnn_num_nodes: 2708
gnn_node_features: 0
gnn_layers: 2
gnn_use_leading: true
gnn_leading_alpha: 0.1
gnn_dtype_name: float16
gnn_dropout: 0.1
gnn_neighbor_num: 10
gnn_ckpt_path: /home/jupyter/deepspeed-test/demos/opt-1.3b/
gnn_ckpt_save_path: ckpts/demos/gnn/
dataset_name: cora
dataset_path: /home/jupyter/deepspeed-test/co-training/dataset/
dataset_tokenized_ids_cache: cache/cora/tokenized_ids_cache.pkl
dataset_padding_width: 512
dataloader_type: dgl
exp_save_dir: ckpts/demos/exp/
